### ISSUE TITLE
[BUG] Plots (garden) unproper sync between host & guest

### ISSUE THREAD

**Issue by DarkMoon1557** [MadMincraftr/NewSR2MP#6]
**Describe the bug**
Created garden does not appear to the friend (guest) if he rejoins game. Growing/harvesting plants is bugged as well (plants do not grow or they can't be collected by both host & guest)

**To Reproduce**
1. Go to the plot (Host & guest)
2. Buy a garden
3. Put in a plant
4. Let the friend rejoin a game
5. Field will be empty for them

**Expected behavior**
Proper syncing and garden planting/harvesting between host & guests

**Host:** 
![Image](https://github.com/user-attachments/assets/d316b76a-a84d-457f-a2c8-edb4aa077c5e)
**Guest:**
![Image](https://github.com/user-attachments/assets/f56c3411-89bb-4e44-bd9d-f4a148a5a276)

**Computer**
 - OS: Windows 11 24H2
 - Mod Version Testing
 - Connection method: LAN

**Comment by TheanMcGarity** [comment]
This is already fixed, in an update ive already posted, unless you can provide logs that tell me its a new error

**Comment by DarkMoon1557** [comment]
Here is logs, installed latest Testing version and it seems the issue is still here.

[25-5-9_0-14-15.log](https://github.com/user-attachments/files/20110736/25-5-9_0-14-15.log)

**Comment by TheanMcGarity** [comment]
Understood. This issue is not seemingly easy to fix, I will work on this a little later, as I do not know why this is happening

**Comment by TheanMcGarity** [comment]
I just realized

**Comment by TheanMcGarity** [comment]
i think i am schizophrenic

**Comment by TheanMcGarity** [comment]
there was this whole bug report i thought i read here

**Comment by TheanMcGarity** [comment]
that wasnt real, it was all in my head

**Comment by TheanMcGarity** [comment]
yeah, this issue is known, i can fix it in the next update, all i have to do is place the plot and plant the stuff on save load

**Comment by TheanMcGarity** [comment]
can you send the client log

**Comment by DarkMoon1557** [comment]
> can you send the client log

Of course, I hope it's the right one :) 
[Player.log](https://github.com/user-attachments/files/20113006/Player.log)

**Comment by TheanMcGarity** [comment]
no

**Comment by TheanMcGarity** [comment]
thats unity log

**Comment by TheanMcGarity** [comment]
i need latest.log for melonloader from the client pc

**Comment by TheanMcGarity** [comment]
I tried to fix it last night but the testers saw a weird, glitched plot, with nothing inside it, not even a dirt floor

**Comment by DarkMoon1557** [comment]
> i need latest.log for melonloader from the client pc

[Latest.log](https://github.com/user-attachments/files/20124953/Latest.log)

**Comment by TheanMcGarity** [comment]
This is still the wrong thing

**Comment by TheanMcGarity** [comment]
I need the log of the player **who joined**

**Comment by TheanMcGarity** [comment]
It says `port started on 7777`

**Comment by TheanMcGarity** [comment]
Not exactly that wording but yea

**Comment by DarkMoon1557** [comment]
> I need the log of the player **who joined**

Guest log: 
[Latest.log](https://github.com/user-attachments/files/20125574/Latest.log)

**Comment by TheanMcGarity** [comment]
This is fixable

**Comment by TheanMcGarity** [comment]
I will work on this later

**Comment by TheanMcGarity** [comment]
Should be fixed in beta update 605 from the discord
